# Site settings
title: Maker Medic Manufacturing
email:
description: >   # this means to ignore newlines until "baseurl:"
 A 3D printing and design service. Flight medic owned and operated. Offering custom and ready to print designs for the medical transport world and beyond.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://makermedicmfg.com" # the base hostname & protocol for your site

twitter_username:
github_username:


# Build settings
markdown: kramdown
